Correcting issues and errors in previous PR (#5)
* Update gbc-hacks.jsonc

Correcting folder name: gbah to gbch

* Update epic.json - Updating launch_arguments

Updating launch_arguments as current does not launch games

* Update amazon.json - Updating launch_arguments

Updating launch_arguments as current does not launch games

* Update gog.json - Updating launch_arguments

Updating launch_arguments as current does not launch games

* Update pcgames.json - Updating launch_arguments

Updating launch_arguments as current does not launch games

* Update epic.json - Updating launch_arguments

Removing new lines from launch_arguments

* Update amazon.json - Updating launch_arguments

Removing new lines from launch_arguments

* Update gog.json - Updating launch_arguments

Removing new lines from launch_arguments

* Update epic.json - Removing extra chatacter from launch_arguments

Removing stray comma from launch_arguments

* Update gb-hacks.json- Updating unique_id

Updating _unique_id_ to resolve conflict with ids in gb.json

* Update gg-hacks.json - Updating unique_id

Updating _unique_id_ to resolve conflict with ids in gg.json

* Update md-hacks.json - Updating unique_id

Updating _unique_id_ to resolve conflict with ids in md.json

* Update gba-hacks.json - Updating unique_id

Updating _unique_id_ to resolve conflict with ids in gba.json

* Update gba-hacks.json - Correcting updated unique_id

Added missing . in unique_id added by mistype

* Update gbc-hacks.json - Updating unique_id

Updating _unique_id_ to resolve conflict with ids in gbc.json

* Update nes-hacks.json - Updating unique_id

Updating _unique_id_ to resolve conflict with ids in nes.json

* Update sfc-hacks.json - Updating unique_id

Updating _unique_id_ to resolve conflict with ids in sfc.json

* Update snes-hacks.json - Updating unique_id

Updating _unique_id_ to resolve conflict with ids in snes.json

* Update genesis-hacks.json - Updating unique_id

Updating _unique_id_ to resolve conflict with ids in genesis.json

* Update gb-hacks.json

correcting unique_id for all emulators due to error made using Find and Replace to update them:
Error: unique_ids were prefixed with "gb-hacks-hacks"
Correction: change prefix to "gb-hacks"